export const main = '#CC0000'
export const primary = '#333333'
export const secondary = '#999999'
export const backGround = '#F2F7F5'
export const otherGround = '#FFFFFE'
export const lightBackGround = '#FFFFFF'